# File: .github/workflows/python-ci.yml
name: Python CI

on:
  push:
    paths:
      - 'python/**'
      - 'tools/**'
      - 'requirements.txt'
  pull_request:
    paths:
      - 'python/**'
      - 'tools/**'
      - 'requirements.txt'

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install flake8

      - name: Lint with flake8
        run: |
          flake8 python/ tools/

      - name: Discover and run tests
        run: |
          if [ -d tests ]; then
            pip install pytest
            pytest --maxfail=1 --disable-warnings -q
          else
            echo "No tests directory; skipping pytest."
          fi
